doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '11'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Alejgarciarodriguez\SymfonyDemo:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'Alejgarciarodriguez\SymfonyDemo\'
                alias: App
